# Quelle und Beschreibung:
Quelle: [einstieg-in-neuronale-netze-mit-tensorflow-und-keras](https://blog.ordix.de/einstieg-in-neuronale-netze-mit-tensorflow-und-keras)

Data in GDrive: 
```
# old Code
# Connect googleDrive

from google.colab import drive
drive.mount('/content/drive')
```





In [17]:
# old Code
# Connect googleDrive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Imports


In [18]:
# Benötigte Imports
import tensorflow as tf
import pandas as pd
from keras.models import Sequential
from keras.layers import InputLayer, Dense, Activation
from sklearn.preprocessing import MinMaxScaler

# used in Own Predictions
import numpy as np



# Prepreocessing

## Read Data

In [19]:
# Einlesen der Daten
data = pd.read_csv('/content/drive/MyDrive/dev/Titanic.csv', encoding='utf-8')



## Convert String data to int Values

In [21]:
d = {0.0: 0, '1': 1}
data['Survived'] = data['Survived'].map(d).fillna(data['Survived'])
data.head()

Unnamed: 0 Class     Sex    Age Survived  Freq
0           1   1st    Male  Child       No     0
1           2   2nd    Male  Child       No     0
2           3   3rd    Male  Child       No    35
3           4  Crew    Male  Child       No     0
4           5   1st  Female  Child       No     0

In [22]:
d = {'No': 0, 'Yes': 1}
data['Survived'] = data['Survived'].map(d).fillna(data['Survived'])
data.head()

Unnamed: 0 Class     Sex    Age  Survived  Freq
0           1   1st    Male  Child         0     0
1           2   2nd    Male  Child         0     0
2           3   3rd    Male  Child         0    35
3           4  Crew    Male  Child         0     0
4           5   1st  Female  Child         0     0

In [23]:
d = {'Male': 1, 'Female': 0}
data['Sex'] = data['Sex'].map(d).fillna(data['Sex'])
data.head()

Unnamed: 0 Class  Sex    Age  Survived  Freq
0           1   1st    1  Child         0     0
1           2   2nd    1  Child         0     0
2           3   3rd    1  Child         0    35
3           4  Crew    1  Child         0     0
4           5   1st    0  Child         0     0

In [26]:
d = {'1st': 1, '2nd': 2, '3rd': 2, 'Crew': 0}
data['Class'] = data['Class'].map(d).fillna(data['Class'])
data.head()

Unnamed: 0  Class  Sex  Age  Survived  Freq
0           1    1.0    1    0         0     0
1           2    2.0    1    0         0     0
2           3    2.0    1    0         0    35
3           4    0.0    1    0         0     0
4           5    1.0    0    0         0     0

In [27]:
d = {'Child': 0, 'Adult': 1}
data['Age'] = data['Age'].map(d).fillna(data['Age'])
data.head()

Unnamed: 0  Class  Sex  Age  Survived  Freq
0           1    1.0    1  0.0         0     0
1           2    2.0    1  0.0         0     0
2           3    2.0    1  0.0         0    35
3           4    0.0    1  0.0         0     0
4           5    1.0    0  0.0         0     0

In [28]:
data

Unnamed: 0  Class  Sex  Age  Survived  Freq
0            1    1.0    1  0.0         0     0
1            2    2.0    1  0.0         0     0
2            3    2.0    1  0.0         0    35
3            4    0.0    1  0.0         0     0
4            5    1.0    0  0.0         0     0
5            6    2.0    0  0.0         0     0
6            7    2.0    0  0.0         0    17
7            8    0.0    0  0.0         0     0
8            9    1.0    1  1.0         0   118
9           10    2.0    1  1.0         0   154
10          11    2.0    1  1.0         0   387
11          12    0.0    1  1.0         0   670
12          13    1.0    0  1.0         0     4
13          14    2.0    0  1.0         0    13
14          15    2.0    0  1.0         0    89
15          16    0.0    0  1.0         0     3
16          17    1.0    1  0.0         1     5
17          18    2.0    1  0.0         1    11
18          19    2.0    1  0.0         1    13
19          20    0.0    1  0.0         1     0
20          21    1.0    0  0.0         1     1
21          22    2.0    0  0.0         1    13
22          23    2.0    0  0.0         1    14
23          24    0.0    0  0.0         1     0
24          25    1.0    1  1.0         1    57
25          26    2.0    1  1.0         1    14
26          27    2.0    1  1.0         1    75
27          28    0.0    1  1.0         1   192
28          29    1.0    0  1.0         1   140
29          30    2.0    0  1.0         1    80
30          31    2.0    0  1.0         1    76
31          32    0.0    0  1.0         1    20

## Splitting the dataset in X and Y 


In [29]:
# Zielvariable (target) und Features (input) auswählen
target = data['Survived']
input = data.drop('Survived', axis=1, )

# Daten skalieren
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(input)
input = scaler.transform(input)
target = target.values

# ML Modell

## Initialazing Modell


In [30]:
# Modell erstellen
model = Sequential()

# Input Layer
model.add(InputLayer(name = "InputLayer", input_shape=(5,)))

# Hidden Layer
model.add(Dense(units=10, name = "HiddenLayer1", activation="relu"))
model.add(Dense(units=5, name = "HiddenLayer2", activation="relu"))

# Output Layer
model.add(Dense(units=1, name = "OutputLayer", activation="sigmoid"))

## Compilling Modell 


In [31]:
# Modell konfigurieren
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Modell trainieren
model.fit(x = input, y = target, epochs = 500)

Epoch 1/500
1/1 [==============================] - 0s 394ms/step - loss: 0.7511 - accuracy: 0.3125
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7497 - accuracy: 0.3438
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7483 - accuracy: 0.3438
Epoch 4/500
1/1 [==============================] - 0s 12ms/step - loss: 0.7470 - accuracy: 0.3438
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7456 - accuracy: 0.3438
Epoch 6/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7443 - accuracy: 0.3438
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7430 - accuracy: 0.3750
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7418 - accuracy: 0.3750
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7405 - accuracy: 0.3750
Epoch 10/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7393 - accuracy: 0.3750
Epoch 11/500
1/1 [========

# Own Predictions

In [32]:
hypMann = [0, 1, 1, 1, 1]
hypFrau = [0, 0, 1, 0, 1]
model.predict(np.array([hypMann, hypFrau]))

1/1 [==============================] - 0s 47ms/step


array([[0.00035265],
       [0.00124519]], dtype=float32)

In [34]:
hypMann = [2, 1, 1, 1, 1]
hypFrau = [2, 0, 1, 0, 1]
model.predict(np.array([hypMann, hypFrau]))

1/1 [==============================] - 0s 24ms/step


array([[0.9999934 ],
       [0.99999434]], dtype=float32)

In [16]:
hypKlasse1 = [1, 1, 1, 0, 1]
hypKlasse3 = [1, 1, 2, 1, 1]
model.predict(np.array([hypKlasse1, hypKlasse3]))

1/1 [==============================] - 0s 29ms/step


array([[0.9984448],
       [0.9948318]], dtype=float32)